### ISSUE TITLE
Compiler or interpreter?

### ISSUE THREAD

**Issue by Spoiledpay** [mirth-lang/mirth#168]
A question about compiling the .exe or linux version? And is there the possibility of being compiled to generate an executable file? Like an .exe?

Do we have any api for Gui windows? Where can I help develop for Windows?

**Comment by typeswitch-dev** [comment]
Hi @Spoiledpay! Welcome!

Currently the mirth compiler only generates C files. You can then compile those C files into executables for Windows, Linux or Mac using a separate C compiler. You can see two ways this is done in `Makefile` (using gcc/clang) and `build.bat` (using VC).

The C target is declared in mirth using `target-c99`, see [here](https://github.com/mirth-lang/mirth/blob/2f3f8cab17817fcd72899e009d79457fa2ec538b/src/mirth.mth#L64) and [here](https://github.com/mirth-lang/mirth/blob/2f3f8cab17817fcd72899e009d79457fa2ec538b/src/snake.mth#L410). When running the compiler on this file, the C file is generated and placed in `bin`.

The generated C code is platform-independent and self-contained. You can add external dependencies in your program by using `def-external`, such as in [these incomplete SDL2 bindings for mirth](https://github.com/mirth-lang/mirth/blob/2f3f8cab17817fcd72899e009d79457fa2ec538b/src/sdl2.mth#L8). There is currently no built-in API for building GUIs or opening windows or anything, but by using `def-external` you could build your own bindings.

If you just want to try making an application, I suggest looking at `snake.mth` and `sdl2.mth` and seeing how they work. If you want to try contribute win32 bindings (or something else) that would be cool too, though I suspect you'll run into big roadblocks right now, because `def-external` isn't very flexible or fleshed out yet.

Please let me know if you have any questions! Thanks!

**Comment by Spoiledpay** [comment]
Hello!.

I tried to understand but I didn't understand the process of generating a new code. Compile native Windows code. exe.
What command line should I use to compile this example here? Demonstrating what the file name would be? hello.mth

||| A simple hello world program to show off the mirth language.
module(examples.hello-world)
import(prelude)
import(platform.posix)

target-c99("hello-world.c",
    "Hello, world!" str-print-ln!)

**Comment by typeswitch-dev** [comment]
So, first of all you need the mirth compiler as an executable, and you have to compile that from the C source file `mirth0.c` found in the `bin` folder. To do this you will need a C compiler. I suggest using MSYS2 & following all the instructions on https://www.msys2.org/ to install MSYS2 and get `gcc` working within MSYS2. I also suggest installing [make](https://packages.msys2.org/package/make) as well by running `pacman -S make` within MSYS2. You can then build the mirth compiler (`bin/mirth0.exe`) by opening the MSYS2 command-line in the mirth project folder and running `make bin/mirth0`.

Once that's done, you can compile mirth code into C, and then turn that C code into an executable that you can run:

1. save the mirth file in the `src` folder as `hello.mth`
2. from the project root, run the command `bin/mirth0.exe hello.mth`. This will produce the C file `hello-world.c` inside the `bin` folder.
3. compile that C file into an executable: `gcc -o bin/hello-world.exe bin/hello-world.c`
4. and run it: `bin/hello-world.exe`

This is a long process, but one day it will be more direct & not require a separate compiler. Mirth is still a WIP though, so it's not exactly user-friendly at the moment ... or stable as a programming language.

Instead of doing these steps manually every time, I suggest editing the `Makefile` and adding some rules. Look at how `snake` is [compiled](https://github.com/mirth-lang/mirth/blob/2f3f8cab17817fcd72899e009d79457fa2ec538b/Makefile#L109) and [run](https://github.com/mirth-lang/mirth/blob/2f3f8cab17817fcd72899e009d79457fa2ec538b/Makefile#L59), for example, and adapt that to your use case. You can try running yourself using `make play-snake` in the MSYS2 command-line. (You'll need to install the [SDL2](https://packages.msys2.org/base/mingw-w64-SDL2) package in MSYS2 to run this.)
