### ISSUE TITLE
Marking an import as inline crashes the compiler

### ISSUE THREAD

**Issue by casuallyblue** [mirth-lang/mirth#249]
Currently it is allowed to mark anything as inline including imports which causes the compiler to throw a segmentation fault on codegen. 
I've tested it by doing `inline:import(std.prelude)` in mirth/main.mth

**Comment by typeswitch-dev** [comment]
Oh no! I think this is probably causing all of std.prelude definitions to be inlined, and inline causes the codegen to crash in some cases (I think recursive definitions). So this is two separate bugs actually:

- the "inline" state (and any other global state) should not be carried over from the parent module. this will fixed by #241 though.
- putting "inline" on certain definitions (e.g. recursive words) causes the codegen to crash as it tries to inline them.
