### ISSUE TITLE
Print functions aren't working on Windows

### ISSUE THREAD

**Issue by arabelladonna** [mirth-lang/mirth#62]
Okay, so I ran my Project Euler problem 1 code in my Windows Subsystem for Linux install of Ubuntu 18.04 and it's printing properly, which means that the issue likely lies somewhere in the implementation of the printing functions.

I tested in MSYS2's MinGW64 versions of GCC and Clang, as well as with cl in Visual Studio.

Expected output (sorry about using an image; WSL is finicky when it comes to selecting terminal output):

![image](https://user-images.githubusercontent.com/48262530/80046165-c4a1e200-84d7-11ea-8c27-84615fb0db74.png)

Output given in MSYS2's MinGW64 terminal (it's the same in the Visual Studio terminal):

```
ari@DESKTOP-1ER5E33 MINGW64 /d/code/github/mirth
$ ./pe1

ari@DESKTOP-1ER5E33 MINGW64 /d/code/github/mirth
$
```

I've tried both `int-print!` and `int-print-ln!` for this particular code. Neither works.

**Comment by sofiafaro** [comment]
Hi Ari, sorry you ran into this! I think the issue was the use of `int-print!` without calling `init-io!` first. I just pushed #63, which changes the implementation of `print!` and `trace!` to remove the need to call `init-io!` so nobody should run into that again. Please let me know if this fixes the issue. Thank you!

**Comment by arabelladonna** [comment]
That fixed it. Thanks!
